name: Java CI SOA3 Rick & Niek

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.6
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Sonarcube
        run: mvn sonar:sonar \
          -Dsonar.host.url="https://sonarqube.avans-informatica-breda.nl" \
          -Dsonar.login=5e5e42932816cc502ad84f00d682bdba48afa9a1