name: Java CI SOA3 Rick & Niek

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Clean Maven install
        run: mvn clean install
      - name: Analyse with SonarQube
        run: mvn -B clean verify sonar:sonar
          -Dsonar.host.url=https://sonarqube.avans-informatica-breda.nl
          -Dsonar.login=5e5e42932816cc502ad84f00d682bdba48afa9a1